linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - revive
    - unconvert
    - unused
    - nolintlint

run:
  build-tags:
    - cleveldb
    - rocksdb
    - badgerdb
    - boltdb

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - text: "leading space"
      linters:
        - nolintlint
